### ISSUE TITLE
Difficulties compiling

### ISSUE THREAD

**Issue by DyamiGrid** [Phildo/expandpass#1]
Hello, and thanks for this tool.

I'd love to utilize it, but unfortunately I'm not really familiar with C++ so I'm having difficulty compiling this into an executable. I'm running windows 10 currently. I've tried using GNU Make tool to compile it, but I get a wide range of errors. Most of them seem to stem from the fact that I don't have the necessary libraries installed for the various #include statements.

I'd love to figure out how to move forward in terms of compiling it myself, but I think the quickest way would be if you shared an executable somehow. Please let me know if you have any advice.

**Comment by Phildo** [comment]
It's a single .cpp file and shouldn't require any libraries. 

If you've installed visual studio 2019 community (for example), you should have access to the `x64 Native Tools Command Prompt for VS 2019` (try typing it in your search bar).

`cd` into the expandpass repository (`cd C:\Users\DynamiGrid\Desktop\expandpass`) and then you should be able to just run `cl gen.cpp`, which will generate `gen.exe` (which you are free to rename to `expandpass.exe` and move wherever you want as a standalone executable).

**Comment by DyamiGrid** [comment]
Thanks for the quick response, using both cl and make tool give dependency errors, beginning with "stdlib.h" 

I have installed cygwin in the hopes that it would address this, but that didn't seem to work.

**Comment by Phildo** [comment]
Thanks for your patience-

Admittedly, windows is not my strong suit, so if anyone knows more about the windows compilation environment and has suggestions, I'm open to them.

That said, I've made a few small changes. Does pulling the latest commit fix anything?

**Comment by puck2** [comment]
I've got the exe compiled on Windows, and when I run it in the command window I can get the `--help` and `--version` prompts to load. I also know it is calling `seed.txt` because if I rename to 'seed2.txt' I get error.

Task manager shows command doing something, but I never get an output... even for test seed. Should I be running this in the cmd prompt or elsewhere? Ran it fine on Ubuntu but banging my head against the wall with Window$.

**Comment by Phildo** [comment]
That's very strange- I'm running Windows 10, and in `x64 Native Tools Command Prompt for VS 2019` (which is a free download with Visual Studio 2019 Community), I can run the following without issue:

`git clone git@github.com:Phildo/expandpass`
`cd expandpass`
`cl gen.cpp`
`gen.exe`

and I get expected output from the included seed.txt. I'll need more information to help debug. Though, if it requires a substantially different setup than I am currently working with, I likely don't have the resources to help...

**Comment by puck2** [comment]
Phildo

Thanks for letting me know!

I've compiled gen.exe but when I run it I get no output.

Would you mind sending me sample syntax of your command? And are you running the command in native tools for VS? Or are you running it on a regular command prompt? And do you have administrator privileges on the command prompt?

Thanks so much! I'd rather not dual boot but I will if I have to (love that rgb led makes me feel like I'm doing something important)


On February 3, 2021 3:16:44 PM EST, Phildo <notifications@github.com> wrote:
>That's very strange- I'm running Windows 10, and in `x64 Native Tools Command Prompt for VS 2019` (which is a free download with Visual Studio 2019 Community), I can run the following without issue:
>
>`git clone git@github.com:Phildo/expandpass`
>`cd expandpass`
>`cl gen.cpp`
>`gen.exe`
>
>and I get expected output from the included seed.txt. I'll need more information to help debug. Though, if it requires a substantially different setup than I am currently working with, I likely don't have the resources to help...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Phildo/expandpass/issues/1#issuecomment-772793437
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by puck2** [comment]
OK - that worked. I had downloaded the Zip, which allowed <cl gen.cpp> to run, but obviously not effectively - thanks for your help

**Comment by puck2** [comment]
Switched back to linux. Using expandpass plus hashcat hybrid rules.

**Comment by ShawnMcGough** [comment]
Another option for Windows users is to use Windows Subsystem for Linux (WSL) - it works great. Expandpass is blazing fast.
