### ISSUE TITLE
Candidate estimation off by factor of 2

### ISSUE THREAD

**Issue by process0** [Phildo/expandpass#3]
I've noticed the candidate estimation can be off by a factor of 2 for larger patterns. I've only noticed this for patterns using a combination of option, sequence, and permutations, no modifier groups.  I'll try to make a sanitized example.  Is this something you have noticed as well?

**Comment by Phildo** [comment]
Yes- "estimations" can have a significant error range, but I would expect the error to mostly stem from modifications.

If you have a factor of 2 incorrect estimation without modifications, that might be a bug- I'd love to see a seed that I could reproduce the error (if you post the seed publicly, please change all contained strings to not expose anyone's potentially personal information).

**Comment by process0** [comment]
After checking the output (no hashcat), the estimation is correct.  The misunderstanding i believe is from having 2 hashes with different iterations when running with hashcat.
